apiVersion: v1
kind: Service
metadata:
  name: performancedb
spec:
  selector:
    app: performancedb
  ports: 
  - protocol: TCP
    port: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: performancedb
  labels:
    app: performancedb
spec:
  selector:
    matchLabels:
      app: performancedb
  template:
    metadata:
      labels:
        app: performancedb
    spec:
      containers:
      - name: performancedb
        image: alimizan/performancedb
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
